### ISSUE TITLE
the function utils.load_chinese_data() doesn't work

### ISSUE THREAD

**Issue by JinChengneng** [jianxu305/nCov2019_analysis#10]
Hey there,

I've found that the function ```utils.load_chinese_data()``` doesn't work. The error has been thrown saying that  ```ValueError: Cannot mask with non-boolean array containing NA / NaN values```.

I would appreciate it if you would take a glance at it.

**Comment by jianxu305** [comment]
The source data format is changed.  I modified my code a little and it should work now.  Please give a try.  Thanks.

**Comment by JinChengneng** [comment]
Thanks a lot for your timely help. The function ```utils.load_chinese_data()``` works well now. 
Unfortunately,  the subsequent function ```utils.aggDaily(data)``` throws another error saying that ```ValueError: ('Some columns are dropped: ', {'continentName', 'countryEnglishName', 'continentEnglishName', 'countryName'})```.
I hope this information would help to fix this problem.

**Comment by jianxu305** [comment]
This is another case that the source data had been changed.  But it's fixed now.  Please give a try.  Thanks.

**Comment by JinChengneng** [comment]
Well, it works as expected now. Thanks for your great effort!
