### ISSUE TITLE
 data = pd.read_csv(DXY_DATA_PATH)

### ISSUE THREAD

**Issue by gsshawn** [jianxu305/nCov2019_analysis#2]
https://raw.github.usercontent.com/BlankerL/DXY-2019-nCoV-Data/master/csv/DXYArea.csv,获取数据的连接这么写可以吗？执行了一下报错了。
URLError: <urlopen error [Errno 61] Connection refused>

**Comment by jianxu305** [comment]
你的拼写有误。应该是
https://raw.githubusercontent.com/BlankerL/DXY-2019-nCoV-Data/master/csv/DXYArea.csv
