### ISSUE TITLE
International data integration

### ISSUE THREAD

**Issue by jianxu305** [jianxu305/nCov2019_analysis#4]
1. John Hopkins:
https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

data in the format of googlesheet
github: https://github.com/CSSEGISandData/COVID-19

2. 2019新型冠状病毒疫情时间序列数据仓库 https://lab.isaaclin.cn/nCoV/

3. Lancet may have something available:
https://www.thelancet.com/coronavirus

**Comment by jiaomaji** [comment]
您好，当我执行：daily_frm = utils.aggDaily(data）函数的时候系统报错，请问如何解决？
![TIM截图20200216135000](https://user-images.githubusercontent.com/51304144/74599812-4550f600-50c3-11ea-8e63-daabf35eb41a.png)

**Comment by qaqaqaaaa** [comment]
> 您好，当我执行：daily_frm = utils.aggDaily(data）函数的时候系统报错，请问如何解决？
> ![TIM截图20200216135000](https://user-images.githubusercontent.com/51304144/74599812-4550f600-50c3-11ea-8e63-daabf35eb41a.png)

我也遇到这个问题，好难受

**Comment by jiaomaji** [comment]
在前天没更新的时候是能够运行的，python我刚学不久，不太懂，是不是因为改变了原来的数据格式啊





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"qaqaqaaaa"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月16日(星期天) 下午4:38
收件人:&nbsp;"jianxu305/nCov2019_analysis"<nCov2019_analysis@noreply.github.com&gt;;
抄送:&nbsp;"星空★真美"<1148545707@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [jianxu305/nCov2019_analysis] International data integration (#4)



 
您好，当我执行：daily_frm = utils.aggDaily(data）函数的时候系统报错，请问如何解决？
 
  
我也遇到这个问题，好难受

**Comment by qaqaqaaaa** [comment]
> 在前天没更新的时候是能够运行的，python我刚学不久，不太懂，是不是因为改变了原来的数据格式啊
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"qaqaqaaaa"<notifications@github.com&gt;; 发送时间:&nbsp;2020年2月16日(星期天) 下午4:38 收件人:&nbsp;"jianxu305/nCov2019_analysis"<nCov2019_analysis@noreply.github.com&gt;; 抄送:&nbsp;"星空★真美"<1148545707@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [jianxu305/nCov2019_analysis] International data integration (#4) 您好，当我执行：daily_frm = utils.aggDaily(data）函数的时候系统报错，请问如何解决？ 我也遇到这个问题，好难受 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

意思是数据来源的格式引起的？？  我也这么猜测的

**Comment by dingtang001** [comment]
utils.py自己增加以下过滤，去掉原始数据中4个字段，在73行后边增加：  

```
  out = out.drop(columns=['provinceEnglishName'])
    out = out.drop(columns=['province_zipCode'])
    out = out.drop(columns=['cityEnglishName'])
    out = out.drop(columns=['city_zipCode'])
```

**Comment by jiaomaji** [comment]
谢谢，我正在努力学习这个文件里的函数和一些用法，挺棒的！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"dingtang001"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月16日(星期天) 晚上7:18
收件人:&nbsp;"jianxu305/nCov2019_analysis"<nCov2019_analysis@noreply.github.com&gt;;
抄送:&nbsp;"星空★真美"<1148545707@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [jianxu305/nCov2019_analysis] International data integration (#4)




utils.py自己增加以下过滤，去掉原始数据中4个字段，在73行后边增加：
   out = out.drop(columns=['provinceEnglishName'])     out = out.drop(columns=['province_zipCode'])     out = out.drop(columns=['cityEnglishName'])     out = out.drop(columns=['city_zipCode'])

**Comment by jianxu305** [comment]
> 您好，当我执行：daily_frm = utils.aggDaily(data）函数的时候系统报错，请问如何解决？
> ![TIM截图20200216135000](https://user-images.githubusercontent.com/51304144/74599812-4550f600-50c3-11ea-8e63-daabf35eb41a.png)

出错信息里面的 new.py 是什么文件？你自己加上去的吗？

**Comment by jiaomaji** [comment]
我自己创建的文件，自己打算练习一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jianxu305"<notifications@github.com&gt;; 
发送时间: 2020年2月16日(星期天) 晚上10:44
收件人: "jianxu305/nCov2019_analysis"<nCov2019_analysis@noreply.github.com&gt;; 
抄送: "星空★真美"<1148545707@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [jianxu305/nCov2019_analysis] International data integration (#4)



 
您好，当我执行：daily_frm = utils.aggDaily(data）函数的时候系统报错，请问如何解决？
 
  
出错信息里面的 new.py 是什么文件？你自己加上去的吗？
 
&mdash;

**Comment by jianxu305** [comment]
> 在前天没更新的时候是能够运行的，python我刚学不久，不太懂，是不是因为改变了原来的数据格式啊
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"qaqaqaaaa"<notifications@github.com&gt;; 发送时间:&nbsp;2020年2月16日(星期天) 下午4:38 收件人:&nbsp;"jianxu305/nCov2019_analysis"<nCov2019_analysis@noreply.github.com&gt;; 抄送:&nbsp;"星空★真美"<1148545707@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [jianxu305/nCov2019_analysis] International data integration (#4) 您好，当我执行：daily_frm = utils.aggDaily(data）函数的时候系统报错，请问如何解决？ 我也遇到这个问题，好难受 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

数据文件的格式没有更新，但是源程序更新过。你可以用 git pull 获得最新的代码。

**Comment by jiaomaji** [comment]
好的，谢谢您，我的问题已经解决了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jianxu305"<notifications@github.com&gt;; 
发送时间: 2020年2月16日(星期天) 晚上10:48
收件人: "jianxu305/nCov2019_analysis"<nCov2019_analysis@noreply.github.com&gt;; 
抄送: "星空★真美"<1148545707@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [jianxu305/nCov2019_analysis] International data integration (#4)



 
在前天没更新的时候是能够运行的，python我刚学不久，不太懂，是不是因为改变了原来的数据格式啊
 …
 ------------------ 原始邮件 ------------------ 发件人: "qaqaqaaaa"<notifications@github.com&gt;; 发送时间: 2020年2月16日(星期天) 下午4:38 收件人: "jianxu305/nCov2019_analysis"<nCov2019_analysis@noreply.github.com&gt;; 抄送: "星空★真美"<1148545707@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题: Re: [jianxu305/nCov2019_analysis] International data integration (#4) 您好，当我执行：daily_frm = utils.aggDaily(data）函数的时候系统报错，请问如何解决？ 我也遇到这个问题，好难受 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
数据文件的格式没有更新，但是源程序更新过。你可以用 git pull 获得最新的代码。
 
&mdash;

**Comment by jianxu305** [comment]
好的。请问你这个问题跟整合国际数据 (Integrate International data) 有关吗？如果无关的话，以后请针对你遇到的困难新开一个 "Issue"，这样大家读起来不容易混淆。谢谢。

**Comment by jiaomaji** [comment]
抱歉，以后我会注意的。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jianxu305"<notifications@github.com&gt;; 
发送时间: 2020年2月16日(星期天) 晚上10:54
收件人: "jianxu305/nCov2019_analysis"<nCov2019_analysis@noreply.github.com&gt;; 
抄送: "星空★真美"<1148545707@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [jianxu305/nCov2019_analysis] International data integration (#4)




好的。请问你这个问题跟整合国际数据 (Integrate International data) 有关吗？如果无关的话，以后请针对你遇到的困难新开一个 "Issue"，这样大家读起来不容易混淆。谢谢。
 
&mdash;

**Comment by jianxu305** [comment]
我知道你们在说什么了，的确是上游数据格式变了。我把程序更新了一下。你们用 git pull 更新就可以运行了。谢谢提醒。
