### ISSUE TITLE
Change in csv in csse_covid_19_daily_reports

### ISSUE THREAD

**Issue by lmlima** [jianxu305/nCov2019_analysis#8]
Starting at 03-22-2020.csv, https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/ changes csv labels.

So, utils.load_jhs_raw() just loads data before 03/22/2020.

**Comment by jianxu305** [comment]
Thanks for pointing this out.  I will fix it today.

**Comment by jianxu305** [comment]
Done.  utils.load_jhs_raw() loads all data now.  The column names from the old dates are converted into the new names to be consistent.
